### ISSUE TITLE
:ghost: falta de informação sobre o projeto

### ISSUE THREAD

**Issue by py-paulo** [wogoo/shop-crud#1]
Seria bom que existissem as seguintes informações no projeto.

* [x] Descrição breve do que se trata a aplicação no *readme* e no projeto.
* [x] Listagem da *features* existentes e em desenvolvimento.
* [x] Print se existente do *front-end* da aplicação.

**Comment by wogoo** [comment]
Good ideas, I will add in the future, probably without a front.

**Comment by wogoo** [comment]
No front for now, thanks for the tips.
